- src: galaxyproject.galaxy
  version: 0.9.16
- src: galaxyproject.nginx
  version: 0.7.0
- src: galaxyproject.postgresql
  version: 1.0.3
- src: natefoo.postgresql_objects
  version: 1.1
- src: geerlingguy.pip
  version: 2.0.0
- src: uchida.miniconda
  version: 0.3.0
- src: usegalaxy_eu.certbot
  version: 0.1.5
- name: galaxyproject.tusd
  version: 0.0.1
- src: cyverse-ansible.singularity
  version: 048c4f178077d05c1e67ae8d9893809aac9ab3b7
- src: gantsign.golang
  version: 2.6.3
- src: galaxyproject.cvmfs
  version: 0.2.13
- src: galaxyproject.repos
  version: 0.0.2
- src: galaxyproject.slurm
  version: 0.1.3
- name: usegalaxy_eu.rabbitmq
  version: 0.1.0
- src: galaxyproject.pulsar
  version: 1.0.8
- src: galaxyproject.gxadmin
  version: 0.0.8
- src: usegalaxy_eu.influxdb
  version: v6.0.7
- src: cloudalchemy.grafana
  version: 0.14.2
- src: dj-wasabi.telegraf
  version: 0.12.0
- src: usegalaxy_eu.tiaas2
  version: 0.0.8
- src: galaxyproject.proftpd
  version: 0.3.1
