# Galaxy, Postgres, Nginx
- src: galaxyproject.galaxy
  version: 0.10.14
- src: galaxyproject.nginx
  version: 0.7.1
- src: galaxyproject.postgresql
  version: 1.1.2
- src: galaxyproject.postgresql_objects
  version: 1.2.0
- src: galaxyproject.miniconda
  version: 0.3.1
- src: usegalaxy_eu.certbot
  version: 0.1.11
# gxadmin (used in cleanup, and later monitoring.)
- src: galaxyproject.gxadmin
  version: 0.0.12
# TUS (uploads)
- name: galaxyproject.tusd
  version: 0.0.1
# CVMFS Support
- src: galaxyproject.cvmfs
  version: 0.2.21
